### ISSUE TITLE
Where can one find the game binaries?

### ISSUE THREAD

**Issue by minorsecond** [pe1rrr/packet-scriptlets#1]
I'd love to implement games on my own BPQ node, but I'm not sure where you found all of those game files. Would you care to share?

**Comment by pe1rrr** [comment]
> I'd love to implement games on my own BPQ node, but I'm not sure where you found all of those game files. Would you care to share?

Googling the file names from the script can resolve the sources quite quickly. I have added a tar archive to the repo for your convenience.
